### ISSUE TITLE
Setup nominatim on ECS using Aurora or RDS

### ISSUE THREAD

**Issue by geohacker** [OpenHistoricalMap/ohm-nominatim#4]

**Comment by geohacker** [comment]
We're very close here #6 but looks like embarrassingly missed the conversations about managed databases. Based on [the FAQ](https://github.com/openstreetmap/Nominatim/blob/master/docs/admin/Faq.md#i-see-the-error-error-permission-denied-for-language-c) Nominatim wouldn't work on RDS because of the custom C functions. [More here](https://github.com/openstreetmap/Nominatim/issues/1377)

This leaves us in a bit of a pickle. Our dockerization and Cloudformation work is still useful so not many hours down the drain. 

To run Nominatim, we'd have to now also run a container with Postgresql but there are a few challenges like persisting storage and DB networking.

@mojodna do you have any thoughts/concerns here? 
cc @danrademacher @jeffreyameyer @batpad

**Comment by danrademacher** [comment]
@jimmyrocks did some work on this over here: https://github.com/OpenHistoricalMap/openhistoricalmap-docker/issues/7

But we could get only three of four C functions rewritten and then never moved to RDS

**Comment by batpad** [comment]
It seems like the best way forward here would be to run a small ec2 running postgres. Migrating the C functions to SQL is definitely going to be significant work - perhaps we can revisit once more progress is made on the main OHM-website DB.

**Comment by sethfitz** [comment]
Porting the Nominatim functions looks much more complicated, as it's localization and i18n-related. Perhaps some of the tsvector functionality could be leaned up, but the lift is substantial enough that using a standalone EC2 instance is a much better bet.

**Comment by geohacker** [comment]
We setup an EC2 for this. Instructions to do this again are in the readme.
